
networks:
  labnet:
    driver: bridge

services:
  postgres:
    image: postgres:16
    container_name: postgres-soa-lab4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Movies
    ports:
      - "5432:5432"
    networks: [ labnet ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  service-a:
    build:
      context: ./backendfilms
      dockerfile: Dockerfile
    container_name: service-a
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/Movies
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SPRING_APPLICATION_NAME=service-a
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks: [ labnet ]
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 30

  oscars-soap:
    build:
      context: ./backend-oscars
      dockerfile: Dockerfile
    container_name: oscars-soap
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVICE_A_URL=http://service-a:8080
    ports:
      - "8083:8081"
    networks: [ labnet ]
    depends_on:
      service-a:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks: [ labnet ]
    depends_on:
      oscars-soap:
        condition: service_started
